jobs:
  run-experiment:
    environment: reliably
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Execute Reliably Plan
      uses: reliablyhq/actions/plan@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        org-id: 8b5fddfd-1da8-4586-934b-f184f0ef7904
        plan-id: abdb883e-6a95-4039-80d1-4a6c0db3118e
        reliably-experiment-extra: '[{"type":"url","provider":"github","topic":"commit","value":"https://github.com/HelloReliably/resilience/tree/main/plans/abdb883e-6a95-4039-80d1-4a6c0db3118e"}]'
        reliably-host: app.reliably.com
        reliably-service-token: ${{ secrets.RELIABLY_SERVICE_TOKEN }}
        working-dir: plans/abdb883e-6a95-4039-80d1-4a6c0db3118e
name: Reliably Plan abdb883e-6a95-4039-80d1-4a6c0db3118e
on:
  workflow_dispatch: null
