name: Reliably Plan Workflow

on:
  workflow_dispatch:

jobs:
  run-experiment:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Execute Reliably Plan
      uses: reliablyhq/actions/plan@main
  