jobs:
  run-experiment:
    environment: reliably
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Execute Reliably Plan
      uses: reliablyhq/actions/plan@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        org-id: 8b5fddfd-1da8-4586-934b-f184f0ef7904
        plan-id: 5cf1c3d8-c5b0-4ffb-b242-9b14703bb57b
        reliably-experiment-extra: '[{"type":"url","provider":"github","topic":"commit","value":"https://github.com/HelloReliably/resilience/tree/main/plans/5cf1c3d8-c5b0-4ffb-b242-9b14703bb57b"}]'
        reliably-host: app.reliably.com
        reliably-service-token: ${{ secrets.RELIABLY_SERVICE_TOKEN }}
        working-dir: plans/5cf1c3d8-c5b0-4ffb-b242-9b14703bb57b
name: Reliably Plan 5cf1c3d8-c5b0-4ffb-b242-9b14703bb57b
on:
  workflow_dispatch: null
